web:
  build: .
  ports:
    - '13000:3000'
  volumes:
    - .:/src:rw
  environment:
    - NODE_ENV=development
  command: >
    sh -c '
    if test -d node_modules;
    then
      echo node_modules_exists ;
    else
      cp -a /tmp/node_modules /src;
    fi && 
    npm install && 
     /usr/local/bin/npm start
    'b