version: '2'

services:
  web:
    build: .
    ports:
      - 3001:3001
    networks:
      - default
    volumes:
      - .:/src:rw
    environment:
      - NODE_ENV=development
    env_file:
      - ./dev_resources/config.env
    command: >
      sh -c '
      if test -d node_modules;
      then
        echo node_modules_exists ;
      else
        cp -a /tmp/node_modules /src;
      fi && 
      npm install && 
       /usr/local/bin/npm start
      '

  nginx:
    build: ./nginx
    ports:
      - 13080:80
    networks:
      - default

networks:
  default: